from __future__ import annotations

import ast
from dataclasses import dataclass

from core.optimizer_core.models import OptimizationCandidate, OptimizationRequest
from core.optimizer_core.patch_service import PatchService


@dataclass(frozen=True, slots=True)
class OptimizationRule:
    rule_id: str
    title: str
    description: str


PYTHON_RULES = [
    OptimizationRule("PY001", "Use augmented assignment", "Replace x = x + y with x += y when the target is identical."),
    OptimizationRule("PY002", "Use set membership", "Replace membership checks against constant lists with set literals."),
    OptimizationRule("PY003", "Prefer direct truthiness", "Replace len(x) > 0 with x when the pattern is simple."),
    OptimizationRule("PY004", "Flag nested loops", "Detect nested loops and ask benchmarks before changing complexity."),
    OptimizationRule("PY005", "Flag dynamic execution", "Detect eval/exec because they block safe optimization."),
    OptimizationRule("PY006", "Flag broad exception handling", "Detect bare except blocks that hide failures."),
    OptimizationRule("PY007", "Keep imports grouped", "Preserve import blocks during code rewriting."),
    OptimizationRule("PY008", "Avoid global lookups", "Suggest local bindings for repeated module-level lookups."),
    OptimizationRule("PY009", "Avoid needless deepcopy", "Suggest shallow copy or targeted copy when safe."),
    OptimizationRule("PY010", "Memoize pure repeated calls", "Suggest memoization for repeatable pure functions."),
]


class RuleBasedOptimizer:
    def __init__(self) -> None:
        self.patch = PatchService()

    def generate_candidates(
        self,
        request: OptimizationRequest,
        analysis: dict[str, object],
        context: list[dict[str, object]],
    ) -> list[OptimizationCandidate]:
        if request.language.lower() != "python":
            return []
        try:
            tree = ast.parse(request.code)
        except SyntaxError:
            return []

        candidates: list[OptimizationCandidate] = []
        candidates.extend(self._rewrite_candidate(request, SameTargetAddAssignTransformer(), PYTHON_RULES[0], 0.92))
        candidates.extend(self._rewrite_candidate(request, ConstantMembershipTransformer(), PYTHON_RULES[1], 0.82))
        candidates.extend(self._rewrite_candidate(request, LenTruthinessTransformer(), PYTHON_RULES[2], 0.62))
        candidates.extend(self._opportunity_candidates(request, analysis))
        candidates.extend(self._analysis_only_candidates(request, analysis))
        return dedupe_candidates(candidates)

    def _rewrite_candidate(
        self,
        request: OptimizationRequest,
        transformer: ast.NodeTransformer,
        rule: OptimizationRule,
        score: float,
    ) -> list[OptimizationCandidate]:
        try:
            original_tree = ast.parse(request.code)
            updated_tree = transformer.visit(original_tree)
            ast.fix_missing_locations(updated_tree)
            updated_code = ast.unparse(updated_tree) + "\n"
        except Exception:
            return []
        if updated_code == request.code or not getattr(transformer, "changed", False):
            return []
        patch = self.patch.create_patch(request.code, updated_code, "uploaded.py")
        return [
            OptimizationCandidate(
                rule_id=rule.rule_id,
                title=rule.title,
                summary=rule.description,
                bottleneck=rule.title,
                patch=patch,
                updated_code=updated_code,
                risk_level="low" if score >= 0.8 else "medium",
                expected_effect="Reduces interpreter work while preserving the same Python behavior for the matched pattern.",
                score=score,
                notes=[f"Generated by local rule {rule.rule_id}.", "Run tests before applying."],
            )
        ]

    def _analysis_only_candidates(
        self,
        request: OptimizationRequest,
        analysis: dict[str, object],
    ) -> list[OptimizationCandidate]:
        findings = analysis.get("static_findings", [])
        if not isinstance(findings, list):
            return []
        candidates: list[OptimizationCandidate] = []
        for finding in findings:
            if not isinstance(finding, dict):
                continue
            message = str(finding.get("message", ""))
            if "Nested loop" in message:
                candidates.append(self._note_candidate(request, PYTHON_RULES[3], message, 0.35))
            elif "eval" in message or "exec" in message:
                candidates.append(self._note_candidate(request, PYTHON_RULES[4], message, 0.3))
            elif "Bare except" in message:
                candidates.append(self._note_candidate(request, PYTHON_RULES[5], message, 0.4))
        return candidates

    def _opportunity_candidates(
        self,
        request: OptimizationRequest,
        analysis: dict[str, object],
    ) -> list[OptimizationCandidate]:
        raw = analysis.get("optimization_opportunities", [])
        if not isinstance(raw, list):
            return []
        candidates: list[OptimizationCandidate] = []
        for item in raw:
            if not isinstance(item, dict):
                continue
            rule = str(item.get("rule", "LOCAL_ANALYSIS_RULE"))
            reason = str(item.get("reason", "Local analyzer found an optimization opportunity."))
            risk = str(item.get("risk", "medium"))
            confidence = float(item.get("confidence", 0.4))
            if rule in {"LIST_MEMBERSHIP_TO_SET", "AUGMENTED_ASSIGNMENT"}:
                continue
            candidates.append(
                OptimizationCandidate(
                    rule_id=rule,
                    title=rule.replace("_", " ").title(),
                    summary=reason,
                    bottleneck=reason,
                    patch="",
                    updated_code=request.code,
                    risk_level=risk,
                    expected_effect="Structured local analysis found this candidate; generate a patch only after tests and context confirm it.",
                    score=confidence,
                    notes=[
                        "Detected by structured analyzer rule engine.",
                        f"Target line: {item.get('target_line', 1)}",
                    ],
                )
            )
        return candidates

    def _note_candidate(
        self,
        request: OptimizationRequest,
        rule: OptimizationRule,
        bottleneck: str,
        score: float,
    ) -> OptimizationCandidate:
        return OptimizationCandidate(
            rule_id=rule.rule_id,
            title=rule.title,
            summary=rule.description,
            bottleneck=bottleneck,
            patch="",
            updated_code=request.code,
            risk_level="medium",
            expected_effect="Requires project context, tests, and benchmarking before producing a safe patch.",
            score=score,
            notes=[f"Detected by local rule {rule.rule_id}.", "No automatic patch generated for this risk level."],
        )


class SameTargetAddAssignTransformer(ast.NodeTransformer):
    changed = False

    def visit_Assign(self, node: ast.Assign) -> ast.AST:
        self.generic_visit(node)
        if len(node.targets) != 1:
            return node
        target = node.targets[0]
        if not isinstance(node.value, ast.BinOp) or not isinstance(node.value.op, ast.Add):
            return node
        if not same_target(target, node.value.left):
            return node
        self.changed = True
        return ast.copy_location(ast.AugAssign(target=target, op=ast.Add(), value=node.value.right), node)


class ConstantMembershipTransformer(ast.NodeTransformer):
    changed = False

    def visit_Compare(self, node: ast.Compare) -> ast.AST:
        self.generic_visit(node)
        if len(node.ops) != 1 or len(node.comparators) != 1:
            return node
        if not isinstance(node.ops[0], (ast.In, ast.NotIn)):
            return node
        comparator = node.comparators[0]
        if not isinstance(comparator, (ast.List, ast.Tuple)):
            return node
        if len(comparator.elts) < 4 or not all(isinstance(item, ast.Constant) for item in comparator.elts):
            return node
        self.changed = True
        node.comparators[0] = ast.Set(elts=comparator.elts)
        return node


class LenTruthinessTransformer(ast.NodeTransformer):
    changed = False

    def visit_Compare(self, node: ast.Compare) -> ast.AST:
        self.generic_visit(node)
        if len(node.ops) != 1 or len(node.comparators) != 1:
            return node
        if not (isinstance(node.ops[0], ast.Gt) and isinstance(node.comparators[0], ast.Constant)):
            return node
        if node.comparators[0].value != 0:
            return node
        call = node.left
        if not (
            isinstance(call, ast.Call)
            and isinstance(call.func, ast.Name)
            and call.func.id == "len"
            and len(call.args) == 1
            and not call.keywords
        ):
            return node
        self.changed = True
        return ast.copy_location(call.args[0], node)


def dedupe_candidates(candidates: list[OptimizationCandidate]) -> list[OptimizationCandidate]:
    seen: set[tuple[str, str]] = set()
    unique: list[OptimizationCandidate] = []
    for candidate in candidates:
        key = (candidate.rule_id, candidate.patch)
        if key in seen:
            continue
        seen.add(key)
        unique.append(candidate)
    return unique


def same_target(left: ast.AST, right: ast.AST) -> bool:
    if isinstance(left, ast.Name) and isinstance(right, ast.Name):
        return left.id == right.id
    if isinstance(left, ast.Attribute) and isinstance(right, ast.Attribute):
        return left.attr == right.attr and same_target(left.value, right.value)
    if isinstance(left, ast.Subscript) and isinstance(right, ast.Subscript):
        return ast.dump(left.slice) == ast.dump(right.slice) and same_target(left.value, right.value)
    return False
